server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    add_header X-Content-Type-Options "nosniff" always;

    location /img/ {
        alias /usr/share/nginx/gpr-img/;
        access_log off;
        expires 1h;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
